### PR TITLE
Refprop viscosity RES model

### PR DESCRIPTION
**Pull request by longemen3000**
a (probably incorrect) implementation of adding a new transport property model for EntropyScaling. Tested with water, the values match within 5%, but it is still greater than the deviations reported in https://doi.org/10.1007/s10765-022-03096-9, so probably something is wrong somewhere.

### CODE REVIEW

**Comment by se-schmitt** [comment]
HI @longemen3000 , I (probably) found the bug. There are two models in the paper, one using the ni parameters (component-specific) and one using global ni parameter (group specific) + one compoent-specific parameter (xi). Now, the deviation to the Refprop model is within 1 %. This shoul probably be validated to the python implementation (will do this tomorrow).

Another thing I modified is the "character" of the models. The FrameworkModel is meant to be a autonomous model. New models are meant to be implemented independently (new types, new params, etc.). Then, no new viscosity types need to be defined, only new models. Does this make sense? I implemented the Refprop model in that way in my commits. I'll make the code cleaner tomorrow.

**Comment by longemen3000** [comment]
Yeah, it makes sense, On the character of models, there are two extremes: making one omni model that holds all possible combinations (like REFPROP, Coolprop) or making one type per model (like Clapeyron, feos and now this package). This PR, more than just adding a new model, is to experiment on how to add more models for different transport properties (in the context of entropy scaling)

**Comment by longemen3000** [comment]
on the last commit (refprop res model from the tests)
```
julia> @btime viscosity(model,1e5,298.15,phase = :l)
  12.800 μs (3 allocations: 80 bytes)
0.0008814119958028551
```
almost no allocations, and most of the time is spent in the calculation of volume, as it should be

**Comment by se-schmitt** [comment]
Very nice! I'll make some changes to make it more general (with other methods in mind). This includes e.g.
- generalizing the `viscosity()`, `thermal_conductivity()`, etc functions and moving them to new file
- defining necessary steps to add new models (which functions need to be defined)
- writing generalized fitting function
- creating a database
Do you have sth to add?

**Pull request merged**
